// <auto-generated />
namespace FMS.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateidentityuser01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateidentityuser01));
        
        string IMigrationMetadata.Id
        {
            get { return "201901060813505_update-identityuser01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
