// <auto-generated />
namespace FMS.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateidentityuseragain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateidentityuseragain));
        
        string IMigrationMetadata.Id
        {
            get { return "201901070045027_update-identity-user-again"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
